apiVersion: apps/v1
kind: Deployment
metadata:
  name: ping-pong
  labels:
    app: ping-pong
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ping-pong
  template:
    metadata:
      labels:
        app: ping-pong
    spec:
      containers:
        - name: ping-pong
          # Build locally with: docker build -t ping-pong:1.9 ./ping_pong
          image: ping-pong:1.9
          imagePullPolicy: IfNotPresent
          env:
            - name: PORT
              value: "8080"
            - name: COUNTER_FILE_PATH
              value: "/shared/pingpong_count.txt"
          ports:
            - name: http
              containerPort: 8080
          volumeMounts:
            - name: shared-data
              mountPath: /shared
      volumes:
        - name: shared-data
          persistentVolumeClaim:
            claimName: shared-data-pvc

