apiVersion: v1
kind: Service
metadata:
  name: ping-pong
  namespace: exercises
  labels:
    app: ping-pong
spec:
  type: LoadBalancer
  selector:
    app: ping-pong
  ports:
    - name: http
      port: 8080
      targetPort: 8080

