apiVersion: apps/v1
kind: Deployment
metadata:
  name: broadcaster
spec:
  template:
    spec:
      containers:
        - name: broadcaster
          env:
            - name: BROADCAST_MODE
              value: "log"
            - name: BROADCAST_URL
              value: ""
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: todo-db-backup
spec:
  suspend: true


