apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app
  namespace: project
  labels:
    app: todo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      containers:
        - name: todo-app
          # Build locally with: docker build -t todo-app:1.13 ./the_project/todo-app
          image: todo-app:1.13
          imagePullPolicy: IfNotPresent
          env:
            - name: PORT
              value: "3000"
            - name: WELCOME_MESSAGE
              value: "Welcome to the Todo App"
            - name: CACHE_DIR
              value: "/cache"
            - name: CACHE_TTL_SECONDS
              value: "600"
            - name: IMAGE_SOURCE_URL
              value: "https://picsum.photos/1200"
          ports:
            - name: http
              containerPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-backend
  namespace: project
  labels:
    app: todo-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-backend
  template:
    metadata:
      labels:
        app: todo-backend
    spec:
      containers:
        - name: todo-backend
          # Build locally with: docker build -t todo-backend:2.2 ./the_project/backend
          image: todo-backend:2.2
          imagePullPolicy: IfNotPresent
          env:
            - name: PORT
              value: "4000"
            - name: TODO_MAXLEN
              value: "140"
          ports:
            - name: http
              containerPort: 4000
          volumeMounts:
            - name: image-cache
              mountPath: /cache
      volumes:
        - name: image-cache
          persistentVolumeClaim:
            claimName: shared-data-pvc

