apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app
  labels:
    app: todo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      containers:
        - name: todo-app
          # Build locally with: docker build -t todo-app:1.12 ./the_project/todo-app
          image: todo-app:1.12
          imagePullPolicy: IfNotPresent
          env:
            - name: PORT
              value: "3000"
            - name: WELCOME_MESSAGE
              value: "Welcome to the Todo App"
            - name: CACHE_DIR
              value: "/cache"
            - name: CACHE_TTL_SECONDS
              value: "600"
            - name: IMAGE_SOURCE_URL
              value: "https://picsum.photos/1200"
          ports:
            - name: http
              containerPort: 3000
          volumeMounts:
            - name: image-cache
              mountPath: /cache
      volumes:
        - name: image-cache
          persistentVolumeClaim:
            claimName: shared-data-pvc

